spring.application.name=shark
spring.datasource.url=jdbc:postgresql://localhost:5432/sharkdb
spring.datasource.username=postgres
spring.datasource.password=postgres

// db가 시작되면 entity를 조회하면서 없는 테이블이 있다면 만들어준다.
spring.jpa.hibernate.ddl-auto=update